name: Generate cli binaries and Release
on:
  push:
    tags:
      - examples/yamabiko/v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '~1.23.3'
      - name: Build binaries
        working-directory: examples/yamabiko
        run: |
          GOOS=linux GOARCH=amd64 go build -o yamabiko-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o yamabiko-darwin-amd64
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            examples/yamabiko/yamabiko-linux-amd64
            examples/yamabiko/yamabiko-darwin-amd64
